// Code generated by internal/gen/listgen. DO NOT EDIT.
//
// The eager List[T] mirror of the Seq[T] operation set. Semantics are
// identical to the Seq operator over AsSeq() — enforced by the C15
// conformance check in list_test.go. Chained List transforms allocate a
// full slice per stage, like Kotlin's List operations.

package catena

import "cmp"

// Filter mirrors Seq.Filter eagerly.
func (l List[T]) Filter(pred func(T) bool) List[T] {
	return List[T](FromSlice([]T(l)).Filter(pred).Collect())
}

// FilterNot mirrors Seq.FilterNot eagerly.
func (l List[T]) FilterNot(pred func(T) bool) List[T] {
	return List[T](FromSlice([]T(l)).FilterNot(pred).Collect())
}

// FilterIndexed mirrors Seq.FilterIndexed eagerly.
func (l List[T]) FilterIndexed(pred func(int, T) bool) List[T] {
	return List[T](FromSlice([]T(l)).FilterIndexed(pred).Collect())
}

// Take mirrors Seq.Take eagerly.
func (l List[T]) Take(n int) List[T] {
	return List[T](FromSlice([]T(l)).Take(n).Collect())
}

// TakeWhile mirrors Seq.TakeWhile eagerly.
func (l List[T]) TakeWhile(pred func(T) bool) List[T] {
	return List[T](FromSlice([]T(l)).TakeWhile(pred).Collect())
}

// TakeLast mirrors Seq.TakeLast eagerly.
func (l List[T]) TakeLast(n int) List[T] {
	return List[T](FromSlice([]T(l)).TakeLast(n).Collect())
}

// Drop mirrors Seq.Drop eagerly.
func (l List[T]) Drop(n int) List[T] {
	return List[T](FromSlice([]T(l)).Drop(n).Collect())
}

// DropWhile mirrors Seq.DropWhile eagerly.
func (l List[T]) DropWhile(pred func(T) bool) List[T] {
	return List[T](FromSlice([]T(l)).DropWhile(pred).Collect())
}

// DropLast mirrors Seq.DropLast eagerly.
func (l List[T]) DropLast(n int) List[T] {
	return List[T](FromSlice([]T(l)).DropLast(n).Collect())
}

// Step mirrors Seq.Step eagerly.
func (l List[T]) Step(n int) List[T] {
	return List[T](FromSlice([]T(l)).Step(n).Collect())
}

// OnEach mirrors Seq.OnEach eagerly.
func (l List[T]) OnEach(f func(T)) List[T] {
	return List[T](FromSlice([]T(l)).OnEach(f).Collect())
}

// Concat mirrors Seq.Concat eagerly.
func (l List[T]) Concat(others ...Seq[T]) List[T] {
	return List[T](FromSlice([]T(l)).Concat(others...).Collect())
}

// Prepend mirrors Seq.Prepend eagerly.
func (l List[T]) Prepend(vals ...T) List[T] {
	return List[T](FromSlice([]T(l)).Prepend(vals...).Collect())
}

// Intersperse mirrors Seq.Intersperse eagerly.
func (l List[T]) Intersperse(sep T) List[T] {
	return List[T](FromSlice([]T(l)).Intersperse(sep).Collect())
}

// IfEmpty mirrors Seq.IfEmpty eagerly.
func (l List[T]) IfEmpty(defaults ...T) List[T] {
	return List[T](FromSlice([]T(l)).IfEmpty(defaults...).Collect())
}

// SortedWith mirrors Seq.SortedWith eagerly.
func (l List[T]) SortedWith(cmp func(a, b T) int) List[T] {
	return List[T](FromSlice([]T(l)).SortedWith(cmp).Collect())
}

// DistinctWith mirrors Seq.DistinctWith eagerly.
func (l List[T]) DistinctWith(eq func(a, b T) bool) List[T] {
	return List[T](FromSlice([]T(l)).DistinctWith(eq).Collect())
}

// Reversed mirrors Seq.Reversed eagerly. O(1)/exact-allocation override.
func (l List[T]) Reversed() List[T] {
	if len(l) == 0 {
		return nil
	}
	out := make([]T, len(l))
	for i, v := range l {
		out[len(l)-1-i] = v
	}
	return List[T](out)
}

// Map mirrors Seq.Map eagerly. O(1)/exact-allocation override.
func (l List[T]) Map[U any](f func(T) U) List[U] {
	if len(l) == 0 {
		return nil
	}
	out := make([]U, 0, len(l))
	for _, v := range l {
		out = append(out, f(v))
	}
	return List[U](out)
}

// MapIndexed mirrors Seq.MapIndexed eagerly. O(1)/exact-allocation override.
func (l List[T]) MapIndexed[U any](f func(int, T) U) List[U] {
	if len(l) == 0 {
		return nil
	}
	out := make([]U, 0, len(l))
	for i, v := range l {
		out = append(out, f(i, v))
	}
	return List[U](out)
}

// FilterMap mirrors Seq.FilterMap eagerly.
func (l List[T]) FilterMap[U any](f func(T) (U, bool)) List[U] {
	return List[U](FromSlice([]T(l)).FilterMap(f).Collect())
}

// FlatMap mirrors Seq.FlatMap eagerly.
func (l List[T]) FlatMap[U any](f func(T) Seq[U]) List[U] {
	return List[U](FromSlice([]T(l)).FlatMap(f).Collect())
}

// FlatMapSlice mirrors Seq.FlatMapSlice eagerly.
func (l List[T]) FlatMapSlice[U any](f func(T) []U) List[U] {
	return List[U](FromSlice([]T(l)).FlatMapSlice(f).Collect())
}

// Scan mirrors Seq.Scan eagerly.
func (l List[T]) Scan[A any](init A, f func(A, T) A) List[A] {
	return List[A](FromSlice([]T(l)).Scan(init, f).Collect())
}

// WithIndex mirrors Seq.WithIndex eagerly.
func (l List[T]) WithIndex() Seq2[int, T] {
	return FromSlice([]T(l)).WithIndex()
}

// ZipWithNext mirrors Seq.ZipWithNext eagerly.
func (l List[T]) ZipWithNext() Seq2[T, T] {
	return FromSlice([]T(l)).ZipWithNext()
}

// MapErr mirrors Seq.MapErr eagerly.
func (l List[T]) MapErr[U any](f func(T) (U, error)) Try[U] {
	return FromSlice([]T(l)).MapErr(f)
}

// FilterErr mirrors Seq.FilterErr eagerly.
func (l List[T]) FilterErr(pred func(T) (bool, error)) Try[T] {
	return FromSlice([]T(l)).FilterErr(pred)
}

// DistinctBy mirrors Seq.DistinctBy eagerly.
func (l List[T]) DistinctBy[K comparable](sel func(T) K) List[T] {
	return List[T](FromSlice([]T(l)).DistinctBy(sel).Collect())
}

// DedupeBy mirrors Seq.DedupeBy eagerly.
func (l List[T]) DedupeBy[K comparable](sel func(T) K) List[T] {
	return List[T](FromSlice([]T(l)).DedupeBy(sel).Collect())
}

// SortedBy mirrors Seq.SortedBy eagerly.
func (l List[T]) SortedBy[K cmp.Ordered](sel func(T) K) List[T] {
	return List[T](FromSlice([]T(l)).SortedBy(sel).Collect())
}

// SortedByDesc mirrors Seq.SortedByDesc eagerly.
func (l List[T]) SortedByDesc[K cmp.Ordered](sel func(T) K) List[T] {
	return List[T](FromSlice([]T(l)).SortedByDesc(sel).Collect())
}

// JoinBy mirrors Seq.JoinBy eagerly.
func (l List[T]) JoinBy[U any, K comparable, R any](other Seq[U], leftKey func(T) K, rightKey func(U) K, combine func(T, U) R) List[R] {
	return List[R](FromSlice([]T(l)).JoinBy(other, leftKey, rightKey, combine).Collect())
}

// Collect mirrors Seq.Collect eagerly. O(1)/exact-allocation override.
func (l List[T]) Collect() []T {
	if len(l) == 0 {
		return nil
	}
	return append([]T(nil), l...)
}

// ToList mirrors Seq.ToList eagerly. O(1)/exact-allocation override.
func (l List[T]) ToList() List[T] {
	return l.Clone()
}

// ForEach mirrors Seq.ForEach eagerly.
func (l List[T]) ForEach(f func(T)) {
	FromSlice([]T(l)).ForEach(f)
}

// ForEachIndexed mirrors Seq.ForEachIndexed eagerly.
func (l List[T]) ForEachIndexed(f func(int, T)) {
	FromSlice([]T(l)).ForEachIndexed(f)
}

// ForEachErr mirrors Seq.ForEachErr eagerly.
func (l List[T]) ForEachErr(f func(T) error) error {
	return FromSlice([]T(l)).ForEachErr(f)
}

// Drain mirrors Seq.Drain eagerly.
func (l List[T]) Drain() {
	FromSlice([]T(l)).Drain()
}

// First mirrors Seq.First eagerly. O(1)/exact-allocation override.
func (l List[T]) First() (T, bool) {
	if len(l) == 0 {
		var zero T
		return zero, false
	}
	return l[0], true
}

// Last mirrors Seq.Last eagerly. O(1)/exact-allocation override.
func (l List[T]) Last() (T, bool) {
	if len(l) == 0 {
		var zero T
		return zero, false
	}
	return l[len(l)-1], true
}

// Single mirrors Seq.Single eagerly.
func (l List[T]) Single() (T, bool) {
	return FromSlice([]T(l)).Single()
}

// ElementAt mirrors Seq.ElementAt eagerly. O(1)/exact-allocation override.
func (l List[T]) ElementAt(i int) (T, bool) {
	return l.Get(i)
}

// Find mirrors Seq.Find eagerly.
func (l List[T]) Find(pred func(T) bool) (T, bool) {
	return FromSlice([]T(l)).Find(pred)
}

// FindLast mirrors Seq.FindLast eagerly.
func (l List[T]) FindLast(pred func(T) bool) (T, bool) {
	return FromSlice([]T(l)).FindLast(pred)
}

// FindIndex mirrors Seq.FindIndex eagerly.
func (l List[T]) FindIndex(pred func(T) bool) int {
	return FromSlice([]T(l)).FindIndex(pred)
}

// FindMap mirrors Seq.FindMap eagerly.
func (l List[T]) FindMap[U any](f func(T) (U, bool)) (U, bool) {
	return FromSlice([]T(l)).FindMap(f)
}

// Any mirrors Seq.Any eagerly.
func (l List[T]) Any(pred func(T) bool) bool {
	return FromSlice([]T(l)).Any(pred)
}

// All mirrors Seq.All eagerly.
func (l List[T]) All(pred func(T) bool) bool {
	return FromSlice([]T(l)).All(pred)
}

// None mirrors Seq.None eagerly.
func (l List[T]) None(pred func(T) bool) bool {
	return FromSlice([]T(l)).None(pred)
}

// Count mirrors Seq.Count eagerly. O(1)/exact-allocation override.
func (l List[T]) Count() int {
	return len(l)
}

// CountWhere mirrors Seq.CountWhere eagerly.
func (l List[T]) CountWhere(pred func(T) bool) int {
	return FromSlice([]T(l)).CountWhere(pred)
}

// IsEmpty mirrors Seq.IsEmpty eagerly. O(1)/exact-allocation override.
func (l List[T]) IsEmpty() bool {
	return len(l) == 0
}

// Fold mirrors Seq.Fold eagerly.
func (l List[T]) Fold[A any](init A, f func(A, T) A) A {
	return FromSlice([]T(l)).Fold(init, f)
}

// FoldIndexed mirrors Seq.FoldIndexed eagerly.
func (l List[T]) FoldIndexed[A any](init A, f func(int, A, T) A) A {
	return FromSlice([]T(l)).FoldIndexed(init, f)
}

// FoldWhile mirrors Seq.FoldWhile eagerly.
func (l List[T]) FoldWhile[A any](init A, f func(A, T) (A, bool)) A {
	return FromSlice([]T(l)).FoldWhile(init, f)
}

// FoldErr mirrors Seq.FoldErr eagerly.
func (l List[T]) FoldErr[A any](init A, f func(A, T) (A, error)) (A, error) {
	return FromSlice([]T(l)).FoldErr(init, f)
}

// FoldBy mirrors Seq.FoldBy eagerly.
func (l List[T]) FoldBy[K comparable, A any](key func(T) K, init func(K) A, f func(A, T) A) map[K]A {
	return FromSlice([]T(l)).FoldBy(key, init, f)
}

// Reduce mirrors Seq.Reduce eagerly.
func (l List[T]) Reduce(f func(T, T) T) (T, bool) {
	return FromSlice([]T(l)).Reduce(f)
}

// GroupBy mirrors Seq.GroupBy eagerly.
func (l List[T]) GroupBy[K comparable](sel func(T) K) map[K][]T {
	return FromSlice([]T(l)).GroupBy(sel)
}

// IndexBy mirrors Seq.IndexBy eagerly.
func (l List[T]) IndexBy[K comparable](sel func(T) K) map[K]T {
	return FromSlice([]T(l)).IndexBy(sel)
}

// TallyBy mirrors Seq.TallyBy eagerly.
func (l List[T]) TallyBy[K comparable](sel func(T) K) map[K]int {
	return FromSlice([]T(l)).TallyBy(sel)
}

// Associate mirrors Seq.Associate eagerly.
func (l List[T]) Associate[K comparable, V any](f func(T) (K, V)) map[K]V {
	return FromSlice([]T(l)).Associate(f)
}

// Partition mirrors Seq.Partition eagerly.
func (l List[T]) Partition(pred func(T) bool) (yes, no []T) {
	return FromSlice([]T(l)).Partition(pred)
}

// MaxBy mirrors Seq.MaxBy eagerly.
func (l List[T]) MaxBy[K cmp.Ordered](sel func(T) K) (T, bool) {
	return FromSlice([]T(l)).MaxBy(sel)
}

// MinBy mirrors Seq.MinBy eagerly.
func (l List[T]) MinBy[K cmp.Ordered](sel func(T) K) (T, bool) {
	return FromSlice([]T(l)).MinBy(sel)
}

// MaxOf mirrors Seq.MaxOf eagerly.
func (l List[T]) MaxOf[K cmp.Ordered](sel func(T) K) (K, bool) {
	return FromSlice([]T(l)).MaxOf(sel)
}

// MinOf mirrors Seq.MinOf eagerly.
func (l List[T]) MinOf[K cmp.Ordered](sel func(T) K) (K, bool) {
	return FromSlice([]T(l)).MinOf(sel)
}

// MinMaxOf mirrors Seq.MinMaxOf eagerly.
func (l List[T]) MinMaxOf[K cmp.Ordered](sel func(T) K) (min, max K, ok bool) {
	return FromSlice([]T(l)).MinMaxOf(sel)
}

// MaxWith mirrors Seq.MaxWith eagerly.
func (l List[T]) MaxWith(cmp func(a, b T) int) (T, bool) {
	return FromSlice([]T(l)).MaxWith(cmp)
}

// MinWith mirrors Seq.MinWith eagerly.
func (l List[T]) MinWith(cmp func(a, b T) int) (T, bool) {
	return FromSlice([]T(l)).MinWith(cmp)
}

// TopNBy mirrors Seq.TopNBy eagerly.
func (l List[T]) TopNBy[K cmp.Ordered](n int, sel func(T) K) []T {
	return FromSlice([]T(l)).TopNBy(n, sel)
}

// BottomNBy mirrors Seq.BottomNBy eagerly.
func (l List[T]) BottomNBy[K cmp.Ordered](n int, sel func(T) K) []T {
	return FromSlice([]T(l)).BottomNBy(n, sel)
}

// SumOf mirrors Seq.SumOf eagerly.
func (l List[T]) SumOf[N Numeric](sel func(T) N) N {
	return FromSlice([]T(l)).SumOf(sel)
}

// ProductOf mirrors Seq.ProductOf eagerly.
func (l List[T]) ProductOf[N Numeric](sel func(T) N) N {
	return FromSlice([]T(l)).ProductOf(sel)
}

// AverageOf mirrors Seq.AverageOf eagerly.
func (l List[T]) AverageOf[N Numeric](sel func(T) N) (float64, bool) {
	return FromSlice([]T(l)).AverageOf(sel)
}

// JoinToString mirrors Seq.JoinToString eagerly.
func (l List[T]) JoinToString(sep string, sel func(T) string) string {
	return FromSlice([]T(l)).JoinToString(sep, sel)
}

// generatedListMethods is the manifest for the C15 conformance check.
var generatedListMethods = []string{
	"Filter",
	"FilterNot",
	"FilterIndexed",
	"Take",
	"TakeWhile",
	"TakeLast",
	"Drop",
	"DropWhile",
	"DropLast",
	"Step",
	"OnEach",
	"Concat",
	"Prepend",
	"Intersperse",
	"IfEmpty",
	"SortedWith",
	"DistinctWith",
	"Reversed",
	"Map",
	"MapIndexed",
	"FilterMap",
	"FlatMap",
	"FlatMapSlice",
	"Scan",
	"WithIndex",
	"ZipWithNext",
	"MapErr",
	"FilterErr",
	"DistinctBy",
	"DedupeBy",
	"SortedBy",
	"SortedByDesc",
	"JoinBy",
	"Collect",
	"ToList",
	"ForEach",
	"ForEachIndexed",
	"ForEachErr",
	"Drain",
	"First",
	"Last",
	"Single",
	"ElementAt",
	"Find",
	"FindLast",
	"FindIndex",
	"FindMap",
	"Any",
	"All",
	"None",
	"Count",
	"CountWhere",
	"IsEmpty",
	"Fold",
	"FoldIndexed",
	"FoldWhile",
	"FoldErr",
	"FoldBy",
	"Reduce",
	"GroupBy",
	"IndexBy",
	"TallyBy",
	"Associate",
	"Partition",
	"MaxBy",
	"MinBy",
	"MaxOf",
	"MinOf",
	"MinMaxOf",
	"MaxWith",
	"MinWith",
	"TopNBy",
	"BottomNBy",
	"SumOf",
	"ProductOf",
	"AverageOf",
	"JoinToString",
}
