package catena

import "slices"

//go:generate go run ./internal/gen/listgen

// List-only methods. The mirrored Seq operation set lives in list_gen.go,
// generated by internal/gen/listgen — edit the Seq methods and re-run
// `go generate`, never the generated file.

// Len returns the number of elements. O(1).
func (l List[T]) Len() int { return len(l) }

// At returns the element at index i, panicking exactly like l[i] on an
// out-of-range index. O(1).
func (l List[T]) At(i int) T { return l[i] }

// Get returns the element at index i; (zero, false) for a negative or
// out-of-range index. O(1).
func (l List[T]) Get(i int) (T, bool) {
	if i < 0 || i >= len(l) {
		var zero T
		return zero, false
	}
	return l[i], true
}

// Slice returns l[i:j] as a List, panicking exactly like the slice
// expression — and, exactly like it, sharing the backing array.
func (l List[T]) Slice(i, j int) List[T] { return l[i:j] }

// Clone returns a shallow copy with a fresh backing array.
func (l List[T]) Clone() List[T] { return List[T](slices.Clone([]T(l))) }

// AsSeq returns a lazy, re-iterable view of the list. The list is not
// copied; mutations are visible to later iterations.
func (l List[T]) AsSeq() Seq[T] { return FromSlice([]T(l)) }

// FoldRight reduces right to left. It exists only on List: a right fold
// needs the whole sequence in memory, which a List already is.
func (l List[T]) FoldRight[A any](init A, f func(T, A) A) A {
	acc := init
	for i := len(l) - 1; i >= 0; i-- {
		acc = f(l[i], acc)
	}
	return acc
}

// Append returns a new List with vals appended. Unlike the built-in
// append, the result ALWAYS has a fresh backing array and never aliases
// l — consistent with every other List transform. Callers who want the
// built-in's amortized behavior can use it directly: List is a []T.
func (l List[T]) Append(vals ...T) List[T] {
	out := make([]T, 0, len(l)+len(vals))
	out = append(out, l...)
	out = append(out, vals...)
	return List[T](out)
}
